### ISSUE TITLE
Puppet v4 support?

### ISSUE THREAD

**Issue by brandfocus** [ghoneycutt/puppet-module-facter#29]
Not sure if we have missed something obvious but we are unable to create any facts in /etc/facter/facts.d with the following config:

Puppet 4.1.0
Facter 2.4.4

init.pp
   
     class { 'facter':
         facts_hash => hiera("facter::facts")
    }

production.yaml

	facter::facts:
	    environment:
	        value: 'production'
	    stack:
	        value: 'webserver'

**Comment by ghoneycutt** [comment]
v4 support is official in v3.0.0

**Comment by ghoneycutt** [comment]
@brandfocus you just specify the bits in production.yaml not the code part
