### ISSUE TITLE
Bump stdlib version to >= 4.0.0

### ISSUE THREAD

**Issue by madAndroid** [ghoneycutt/puppet-module-facter#34]
Hi,

Would you consider bumping the stdlib version in the metadata.json to be `>= 4.0.0` ? I've got other module dependencies that have that version requirement (`jfryman/nginx` being just one of them)

**Comment by ghoneycutt** [comment]
Dependencies are for a given module. This module does not yet require stdlib >= 4.0.0 so it does not make sense to state that.

stdlib versions 3, 4 and 5 will be compatible with Puppet v3 and v4 so you are all good.

https://github.com/puppetlabs/puppetlabs-stdlib#version-compatibility

**Comment by madAndroid** [comment]
Okay, thanks - I'll continue to use my fork of your module then. I use librarian puppet to manage dependencies; when both your module and jfryman/nginx are included within the same Puppetfile, the dependency resolution fails, since that module requires >= 4.0.0, and your module doesn't satisfy that dependency. I guess that might be one of the reasons that there are 17 forks of this module.

**Comment by madAndroid** [comment]
> stdlib versions 3, 4 and 5 will be compatible with Puppet v3 and v4 so you are all good.

Nope, not all good - a few modules I use require stdlib >= 4.0.0 .. this module was causing dependency resolution to fail, and it took me a little while to track that down. No worries, I'll continue to use the fork.
Just out of interest, is there any particular reason that it can't use stdlib >= 4.0.0 ?
