### ISSUE TITLE
Restart puppet-agent on facter package update

### ISSUE THREAD

**Issue by jyaworski** [ghoneycutt/puppet-module-facter#45]
Whenever facter is updated, the puppet agent should be restarted to take advantage of it.

Internally, we had a bug where the last_report_summary.yml file format changed (or something like that) and it was causing weird problems. A restart of the service fixed it.

**Comment by ghoneycutt** [comment]
This module is not tightly coupled to the management of the puppet service. I would recommend not running the agent as a service and instead running it from cron. If you would like this functionality, I would have your class that manages the puppet agent include this facter class and have your service subscribe to the facter package.

**Comment by jyaworski** [comment]
Would it be reasonable to add a parameter like <code>manage_puppet</code> that could use resource collection to add a subscribe to that service?

**Comment by ghoneycutt** [comment]
No, because people manage puppet in all sorts of manners and tightly coupling this module to the puppet service does not make sense.

If you use my Puppet module to manage puppet and would want to couple that with this, that would be OK.

https://github.com/ghoneycutt/puppet-module-puppet
