### ISSUE TITLE
You are assuming that the user uses the same hiera 'key' that you do

### ISSUE THREAD

**Issue by felipe1982** [ghoneycutt/puppet-module-facter#48]
Hello.

Thank you for your module. I'd like to ask a question, as I am still learning  a lot about puppet.

Here > https://github.com/ghoneycutt/puppet-module-facter/blob/master/manifests/init.pp#L127
it appears that we are assuming that the user will be using the hiera key `facter::facts_hash` but that might no always be the case. Is that a problem?

**Comment by ghoneycutt** [comment]
Thanks for reporting this issue. It will always be the case due to how puppet looks up parameters.
