### ISSUE TITLE
puppet 4 compliance -- usage of deprecated methods

### ISSUE THREAD

**Issue by Falkor** [ghoneycutt/puppet-module-facter#52]
Using this module under puppet (4.10.0) raises a couple of deprecation warnings listed below: 

| File                       | Line | Warning message                                                                                                 |
|----------------------------|------|-----------------------------------------------------------------------------------------------------------------|
| [`facter/manifests/init.pp`](../blob/master/manifests/init.pp#L26) |   26 | "This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String."       |
| [`facter/manifests/init.pp`](../blob/master/manifests/init.pp#L28) |   28 | "This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Absolute_Path" |
| [`facter/manifests/init.pp`](../blob/master/manifests/init.pp#L30) |   30 | "Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]"            |
| [`facter/manifests/init.pp`](../blob/master/manifests/init.pp#L39) |   39 | "This method is deprecated, please use match expressions with Stdlib::Compat::String instead"                   |
| [`facter/manifests/init.pp`](../blob/master/manifests/init.pp#L42) |   42 | "This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool"          |
| [`facter/manifests/init.pp`](../blob/master/manifests/init.pp#L132) |  132 | "Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Hash" |

Not sure how to properly upgrade the code (and the release) to prevent these warnings to appear

**Comment by ghoneycutt** [comment]
Thanks! This will be helpful as we move to drop support for Puppet v3 and fully embrace the functionality of Puppet v4. Currently the module works for both.

**Comment by Falkor** [comment]
Ok ;)

**Comment by ghoneycutt** [comment]
This is being addressed in #57 

Thank you!
