### ISSUE TITLE
Update README facts_d_group

### ISSUE THREAD

**Issue by NissesSenap** [ghoneycutt/puppet-module-facter#55]
Hi

Saw the following in the README, since i don't wan't to change anything else i didn't see any reason to create a commit but it would be nice to fix during the next commit:

**facts_d_group**
Group of facst_file.
Default: root

**facts_d_mode**
Four digit mode of facts_file.
Default: 0644

It should be 
facts_file_group
and 
facts_file_mode

**Comment by ghoneycutt** [comment]
Thanks for creating this issue. I do not understand what you mean. Could you provide the expected behavior and then what you received or send a pull request.

**Comment by NissesSenap** [comment]
You have been to fast with the copy and paste, if you check in README.md

facts_file_owner
----------------
Owner of facts_file.

- *Default*: root

facts_d_group
-------------
Group of facst_file.

- *Default*: root

facts_d_mode
------------
Four digit mode of facts_file.

- *Default*: 0644

It should say facts_file_mode and facts_file_group. If you search in the file you will see facts_d_mode and facts_d_group two times. But you have written a correct description.

**Comment by ghoneycutt** [comment]
I see now! Got it fixed. Thanks again!

**Comment by ghoneycutt** [comment]
https://github.com/ghoneycutt/puppet-module-facter/commit/e004051dcdf0df45ab6403a0fc8409ca204481bc
