### ISSUE TITLE
Puppet 5 support

### ISSUE THREAD

**Issue by treydock** [ghoneycutt/puppet-module-facter#57]
Similar to what was done on pam module.  Figured make this a place to discuss changes for v4.0.0.

**Comment by treydock** [comment]
@ghoneycutt One thing I'd like to add is optional management of /etc/puppetlabs/facter/facter.conf.  I have the need to force facter CLI to load pluginsync facts.d and seemed like managing the facter conf was appropriate for this module.

**Comment by ghoneycutt** [comment]
Thanks @treydock !! Your help is very much appreciated.

**Comment by ghoneycutt** [comment]
- [x] module hiera data (not doing as there isn't OS specific data until we add windows support)
- [ ] use new readme format (https://github.com/ghoneycutt/puppet-module-bind/blob/master/README.md)
- [ ] use puppet strings
- [ ] enable github pages for puppet strings docs
- [ ] Have @Phil-Friderici sign off on the spec tests
- [ ] Add support for facter.conf

**Comment by treydock** [comment]
Any best practice on community modules using lookup() instead of hiera_hash()?  Would logic be okay that if `$facts_hash_hiera_merge` is true, do a deep merge, otherwise just do normal lookup?  Seems like deep merge should somehow be optional, I know in my environment I have common.yaml facts hashes and then disable merging in some other levels of hiera.  Might be a topic for mailing list?

**Comment by ghoneycutt** [comment]
it should default to true and definitely use lookup(). @Phil-Friderici made a change recently to the yum module at https://github.com/ghoneycutt/puppet-module-yum/pull/24/commits/5e1de21faf50fa04f39e3108c6c2caf2025f748e

**Comment by ghoneycutt** [comment]
This is happening in #68 which is prepping for a major version bump!
