### ISSUE TITLE
Support JSON and YAML formats

### ISSUE THREAD

**Issue by nmaludy** [ghoneycutt/puppet-module-facter#65]
Would be cool to support JSON and YAML formats so things like hashes and arrays could be written to fact files.

Thoughts on what it might look like:

```puppet
array_data = ['a', 'b', 'c']

facter::fact { 'array_data':
  value  => $array_data,
  format => 'json',
}
```

```puppet
hash_data = {'a' => 'value', 'b' => 'data'}

facter::fact { 'hash_data':
  value  => $hash_data,
  format => 'yaml',
}
```

**Comment by aba-rechsteiner** [comment]
+1

**Comment by ghoneycutt** [comment]
I implemented this with `facter::structured_data_fact` in #68 
It does not let you pick between yaml and json, but it shouldn't matter since we are totally managing that file. I went with YAML btw.

**Comment by nmaludy** [comment]
Awesome! That is totally cool with me!
